import { IconType } from 'react-icons'
import {
  SiHtml5,
  SiCss,
  SiJavascript,
  SiTypescript,
  SiReact,
  SiNextdotjs,
  SiTailwindcss,
  SiShadcnui,
  SiMui,
  SiNodedotjs,
  SiExpress,
  SiMongodb,
  SiMysql,
  SiDocker,
  SiGit,
  SiGithub,
  SiIntellijidea,
} from 'react-icons/si'
import { FaAws } from 'react-icons/fa6'
import { VscVscode } from 'react-icons/vsc'
import { TbBrandAzure, TbBinaryTree, TbSitemap } from 'react-icons/tb'

export const SKILL_ICONS: Record<string, IconType> = {
  HTML5: SiHtml5,
  CSS3: SiCss,
  JavaScript: SiJavascript,
  TypeScript: SiTypescript,
  'React.js': SiReact,
  'Next.js': SiNextdotjs,
  'Tailwind CSS': SiTailwindcss,
  Shadcn: SiShadcnui,
  'Material UI': SiMui,
  'Node.js': SiNodedotjs,
  'Express.js': SiExpress,
  MongoDB: SiMongodb,
  MySQL: SiMysql,
  'Azure Blob Storage': TbBrandAzure,
  AWS: FaAws,
  Docker: SiDocker,
  'VS Code': VscVscode,
  Git: SiGit,
  GitHub: SiGithub,
  'IntelliJ IDEA': SiIntellijidea,
  'Data Structures & Algorithms': TbBinaryTree,
  'Low Level Design': TbSitemap,
}

export const SKILL_COLORS: Record<string, string> = {
  HTML5: '#E34F26',
  CSS3: '#1572B6',
  JavaScript: '#F7DF1E',
  TypeScript: '#3178C6',
  'React.js': '#61DAFB',
  'Next.js': '#FFFFFF',
  'Tailwind CSS': '#38BDF8',
  Shadcn: '#FFFFFF',
  'Material UI': '#007FFF',
  'Node.js': '#3C873A',
  'Express.js': '#FFFFFF',
  MongoDB: '#47A248',
  MySQL: '#4479A1',
  'Azure Blob Storage': '#0078D4',
  AWS: '#FF9900',
  Docker: '#2496ED',
  'VS Code': '#007ACC',
  Git: '#F05032',
  GitHub: '#FFFFFF',
  'IntelliJ IDEA': '#FE315D',
  'Data Structures & Algorithms': '#F59E0B',
  'Low Level Design': '#A78BFA',
}
